# Generated by Django 5.0.6 on 2025-12-16 23:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('indicator', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(default=10)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=20, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Compliant', 'Compliant'), ('Non-Compliant', 'Non-Compliant'), ('Not Applicable', 'Not Applicable')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('form_schema', models.JSONField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicators',
                'ordering': ['section', 'standard', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drive_is_connected', models.BooleanField(default=False)),
                ('drive_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_root_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('certificate', 'Certificate'), ('note', 'Note'), ('link', 'Link')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_view_link', models.URLField(blank=True, max_length=500, null=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.indicator')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'db_table': 'evidence',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.project'),
        ),
    ]
