# Generated by Django 5.0.6 on 2025-12-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidence',
            name='evidence_ind_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='indicator',
            name='indicator_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='indicator',
            name='indicator_proj_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_created_at_idx',
        ),
    ]
